name: destination_repository
description: The repo that handles ZC Tour Spots
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.1
  cloud_firestore: ^4.9.2
  rxdart: ^0.27.7
  # equatable
  # firebase_auth
  # cloud_firestore
  # firebase_storage
  # rxdart
  # path

dev_dependencies:
# Suggested code may be subject to a license. Learn more: ~LicenseLog:2643661951.
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
