name: user_repository
description: The repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  # firebase_storage
  rxdart: ^0.27.7
  google_sign_in: ^6.2.1
  # path

dev_dependencies:
# Suggested code may be subject to a license. Learn more: ~LicenseLog:2643661951.
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
